### ISSUE TITLE
ModuleNotFoundError: No module named 'zwift_patch'

### ISSUE THREAD

**Issue by Veldkornet** [snicker/zwift_hass#44]
After updating to version 3.3.2, I'm getting the following error and the integration won't load:

```
ConnectionResetError: Cannot write to closing transport
2023-09-17 08:37:06.230 ERROR (MainThread) [custom_components.zwift.sensor] Could not create Zwift sensor named 'Zwift'!
Traceback (most recent call last):
  File "/config/custom_components/zwift/sensor.py", line 124, in async_setup_platform
    await zwift_data._connect()
  File "/config/custom_components/zwift/sensor.py", line 344, in _connect
    from zwift_patch import zwift_messages_pb2 as new_pb2
ModuleNotFoundError: No module named 'zwift_patch'
```

**Comment by snicker** [comment]
fixed in https://github.com/snicker/zwift_hass/releases/tag/v3.3.3

should have known better than to deploy this without testing, silly import behavior inside custom components

**Comment by Veldkornet** [comment]
Woohoo! After months of nothing, my Zwift integration finally works again 🎉🥳
